let system = [{
    "column": "爱回购",
    "icon": 'linecons-star',
    "list": [{
        "title": "app下载",
        "image": "../assets/images/logos/aihuigou.png",
        "url": "http://www.wangluodaikuankouzi.com/recycling/pages/aiguigou-download.html",
        "content":'内容:...'
    }, {
        "title": "线上h5",
        "image": "../assets/images/logos/dribbble.png",
        "url": "http://www.wangluodaikuankouzi.com/recycling/pages/user-login.html",
        "content": '内容:...'
    }]
}, {
    "column": "小通分期",
    "icon": 'linecons-star',
    "list": [{
        "title": "预发布-产品2",
        "image": "../assets/images/logos/test.png",
        "url": "http://test.h5.credan.com/cashloan/pages/index.html?productId=2&channelSid=1&firmId=23",
        "content": '内容:...'
    }, {
        "title": "预发布-产品10",
        "image": "../assets/images/logos/test.png",
        "url": "http://test.h5.credan.com/cashloan/pages/index.html?productId=10&channelSid=1&firmId=25",
        "content": '内容:...'
    }, {
        "title": "线上-产品2",
        "image": "../assets/images/logos/dribbble.png",
        "url": "http://www.honghkj.com/pages/index.html?productId=2&channelSid=1&firmId=23",
        "content": '内容:...'
    },  {
        "title": "线上-产品10",
        "image": "../assets/images/logos/dribbble.png",
        "url": "http://www.honghkj.com/pages/index.html?productId=10&channelSid=tiqianba1&firmId=25",
        "content": '内容:...'
    }, {
        "title": "app登录下载",
        "image": "../assets/images/logos/tiqianbao.png",
        "url": "http://www.honghkj.com/pages/app-register.html?productId=10&channelSid=tiqianbao1&firmId=25",
        "content": '内容:...'
    },{
        "title": "app",
        "image": "../assets/images/logos/tiqianbao.png",
        "url": "http://www.honghkj.com/pages/app-download.html",
        "content": '内容:...'
    }, {
        "title": "美工图",
        "image": "../assets/images/logos/design.png",
        "url": "https://lanhuapp.com/web/#/item/project/board?pid=b316220c-c3b1-446a-bfd7-20fef40f93a3",
        "content": '内容:...'
    }, {
        "title": "推荐位",
        "image": "../assets/images/logos/manage.png",
        "url": "http://47.98.136.225:7002/index.html?system=app_cashloan",
        "content": '内容:...'
    }]
}, {
    "column": "黑卡",
    "icon": 'linecons-star',    
    "list": [{
        "title": "预发布",
        "image": "../assets/images/logos/test.png",
        "url": "http://test.h5.credan.com/blackcard/pages/index.html?productId=3&channelSid=1&firmId=24",
        "content": '内容:...'
    }, {
        "title": "线上",
        "image": "../assets/images/logos/dribbble.png",
        "url": "http://blackcard.wangluodaikuankouzi.com/pages/index.html?productId=3&channelSid=1&firmId=24",
        "content": '内容:...'
    }, {
        "title": "app",
        "image": "../assets/images/logos/heika.png",
        "url": "http://blackcard.wangluodaikuankouzi.com/pages/app-download.html",
        "content": '内容:...'
    },  {
        "title": "美工图",
        "image": "../assets/images/logos/design.png",
        "url": "https://lanhuapp.com/web/#/item/project/board?pid=5ce9c607-ad7f-4665-8b22-b2da3a83ca6d",
        "content": '内容:...'
    } ,{
        "title": "推荐位",
        "image": "../assets/images/logos/manage.png",
        "url": "http://47.96.8.95:7002/index.html?system=app_blackcard",
        "content": '内容:...'
    }, {
        "title": "推荐位1",
        "image": "../assets/images/logos/manage.png",
        "url": "http://47.98.136.225:7002/index.html?system=app_blackcard",
        "content": '内容:...'
    }, ]
}, {
    "column": "风驰系统",
    "icon": 'linecons-star',
    "list": [{
        "title": "预发布",
        "image": "../assets/images/logos/test.png",
        "url": "http://47.99.163.162:8085",
        "content": '内容:...'
    }, {
        "title": "线上",
        "image": "../assets/images/logos/dribbble.png",
        "url": "http://47.99.198.56:8085",
        "content": '内容:...'
    }, {
        "title": "美工图",
        "image": "../assets/images/logos/design.png",
        "url": "https://lanhuapp.com/web/#/item/project/board?pid=dcf4ec97-3c85-416d-80cb-5182acf5cad5",
        "content": '内容:...'
    }]
}, {
    "column": "享税安",
    "icon": 'linecons-star',
    "list": [{
        "title": "官网",
        "image": "../assets/images/logos/dribbble.png",
        "url": "http://www.xiangshuian.net",
        "content":'内容:...'
    }]
},{
    "column": "币有钱",
    "icon": 'linecons-star',
    "list": [{
        "title": "官网",
        "image": "../assets/images/logos/dribbble.png",
        "url": "http://www.danhkj.com",
        "content":'内容:...'
    }]
}, {
    "column": "swagger-ip",
    "icon": 'linecons-star',
    "list": [{
        "title": "预发布",
        "image": "../assets/images/logos/document.png",
        "url": "http://47.99.163.162:8762/swagger-ui.html#/",
        "content": '内容:...'
    }, {
        "title": "线上",
        "image": "../assets/images/logos/document.png",
        "url": "http://47.98.136.225:8762/swagger-ui.html#/",
        "content": '内容:...'
    }]
}, {
    "column": "swagger-文档",
    "icon": 'linecons-star',
    "list": [ {
        "title": "Loan",
        "image": "../assets/images/logos/document.png",
        "url": "http://47.99.163.162:7001/swagger-ui.html#/",
        "content": '内容:...'
    }, {
        "title": "LoanMgmt",
        "image": "../assets/images/logos/document.png",
        "url": "http://47.99.163.162:7004/swagger-ui.html#/",
        "content": '内容:...'
    }, {
        "title": "loan.report",
        "image": "../assets/images/logos/document.png",
        "url": "http://47.99.163.162:7005/swagger-ui.html#/",
        "content": '内容:...'
    }, {
        "title": "channel",
        "image": "../assets/images/logos/document.png",
        "url": "http://47.99.163.162:7010/swagger-ui.html#/",
        "content": '内容:...'
    },{
        "title": "INSTUFF",
        "image": "../assets/images/logos/document.png",
        "url": "http://47.99.163.162:8065/swagger-ui.html#/",
        "content": '内容:...'
    },]
}];